<h1>Výjimky</h1>
<p>O <a href="naucse:page?lesson=beginners/print">chybových výpisech</a> už v tomto
kurzu byla zmínka: Python si postěžuje, řekne, kde je chyba, a ukončí program.
O chybách se toho ale dá říct mnohem víc.</p>
<h2>Výpisy chyb</h2>
<p>Na začátku si ukážeme (nebo zopakujeme), jak Python vypíše chybu, která
nastane v zanořené funkci:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">vnejsi_funkce</span><span class="p">():</span>
    <span class="k">return</span> <span class="n">vnitrni_funkce</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>

<span class="k">def</span> <span class="nf">vnitrni_funkce</span><span class="p">(</span><span class="n">delitel</span><span class="p">):</span>
    <span class="k">return</span> <span class="mi">1</span> <span class="o">/</span> <span class="n">delitel</span>

<span class="nb">print</span><span class="p">(</span><span class="n">vnejsi_funkce</span><span class="p">())</span>
</pre></div><!-- XXX: Highlight the line numbers -->

<div class="highlight"><pre><span></span><span class="x">Traceback (most recent call last):          </span>
  File <span class="nb">&quot;/tmp/ukazka.py&quot;</span>, line <span class="m">7</span>, in <span class="n">&lt;module&gt;</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">vnejsi_funkce</span><span class="p">())</span>
  File <span class="nb">&quot;/tmp/ukazka.py&quot;</span>, line <span class="m">2</span>, in <span class="n">vnejsi_funkce</span>
    <span class="k">return</span> <span class="n">vnitrni_funkce</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>
  File <span class="nb">&quot;/tmp/ukazka.py&quot;</span>, line <span class="m">5</span>, in <span class="n">vnitrni_funkce</span>
    <span class="k">return</span> <span class="mi">1</span> <span class="o">/</span> <span class="n">delitel</span>
<span class="gr">ZeroDivisionError</span>: <span class="n">division by zero</span>
</pre></div><p>Všimni si, že každá funkce, jejíž volání vedlo k chybě, je uvedena ve výpisu.
Skutečná chyba (tedy místo, které musíme opravit)
je pravděpodobně poblíž některého z těchto volání.
V našem případě bychom asi neměly volat
<code>vnitrni_funkce</code> s argumentem <code>0</code>.
A nebo by <code>vnitrni_funkce</code> měla být na nulu
připravená a dělat v tomto případě něco jiného.</p>
<p>Python nemůže vědět, na kterém místě by se chyba měla opravit, a tak ukáže vše.
Ve složitějších programech se to bude hodit.</p>
<h2>Vyvolání chyby</h2>
<p>Chybu neboli <em>výjimku</em> (angl. <em>exception</em>) můžeš vyvolat i sama,
pomocí příkazu <code>raise</code>.
Za příkaz dáš jméno výjimky a pak do závorek nějaký popis toho, co je špatně.</p>
<div class="highlight"><pre><span></span><span class="n">VELIKOST_POLE</span> <span class="o">=</span> <span class="mi">20</span>

<span class="k">def</span> <span class="nf">over_cislo</span><span class="p">(</span><span class="n">cislo</span><span class="p">):</span>
    <span class="k">if</span> <span class="mi">0</span> <span class="o">&lt;=</span> <span class="n">cislo</span> <span class="o">&lt;</span> <span class="n">VELIKOST_POLE</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;OK!&#39;</span><span class="p">)</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;Čislo </span><span class="si">{n}</span><span class="s1"> není v poli!&#39;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">n</span><span class="o">=</span><span class="n">cislo</span><span class="p">))</span>
</pre></div><p>Všechny typy výjimek, které jsou zabudované
v Pythonu, jsou popsané <a href="https://docs.python.org/3.2/library/exceptions.html#exception-hierarchy">v dokumentaci</a>.</p>
<p>Pro nás jsou (nebo budou) důležité tyto:</p>
<div class="highlight"><pre><code>BaseException
 ├── SystemExit                     vyvolána funkcí exit()
 ├── KeyboardInterrupt              vyvolána po stisknutí Ctrl+C
 ╰── Exception
      ├── ArithmeticError
      │    ╰── ZeroDivisionError    dělení nulou
      ├── AssertionError            nepovedený příkaz `assert`
      ├── AttributeError            neexistující atribut, např. 'abc'.len
      ├── ImportError               nepovedený import
      ├── LookupError
      │    ╰── IndexError           neexistující index, např. 'abc'[999]
      ├── NameError                 použití neexistujícího jména proměnné
      │    ╰── UnboundLocalError    použití proměnné, která ještě nebyla nastavená
      ├── SyntaxError               špatná syntaxe – program je nečitelný/nepoužitelný
      │    ╰── IndentationError     špatné odsazení
      │         ╰── TabError        kombinování mezer a tabulátorů
      ├── TypeError                 špatný typ, např. len(9)
      ╰── ValueError                špatná hodnota, např. int('xyz')</code></pre></div><h2>Ošetření chyby</h2>
<p>A proč jich je tolik druhů?
Abys je mohla chytat!
Následující funkce je připravená na to, že
funkce <code>int</code> může selhat, pokud uživatel nezadá číslo:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
    <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">&#39;Zadej číslo: &#39;</span><span class="p">)</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">cislo</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
    <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;To nebylo číslo! Pokračuji s nulou.&#39;</span><span class="p">)</span>
        <span class="n">cislo</span> <span class="o">=</span> <span class="mi">0</span>
    <span class="k">return</span> <span class="n">cislo</span>
</pre></div><p>Jak to funguje?
Příkazy v bloku uvozeném příkazem <code>try</code> se normálně provádějí, ale když
nastane uvedená výjimka, Python místo ukončení programu provede
všechno v bloku <code>except</code>.
Když výjimka nenastane, blok <code>except</code> se přeskočí.</p>
<p>Když odchytáváš obecnou výjimku,
chytnou se i všechny podřízené typy výjimek –
například <code>except ArithmeticError:</code> zachytí i <code>ZeroDivisionError</code>.
A <code>except Exception:</code> zachytí všechny
výjimky, které běžně chceš zachytit.</p>
<h2>Nechytej je všechny!</h2>
<p>Většinu chyb ale není potřeba ošetřovat.</p>
<p>Nastane-li nečekaná situace, je téměř vždy
<em>mnohem</em> lepší program ukončit, než se snažit
pokračovat dál počítat se špatnými hodnotami.
Navíc chybový výstup, který Python standardně
připraví, může hodně ulehčit hledání chyby.</p>
<p>„Ošetřování” chyb jako <code>KeyboardInterrupt</code>
je ještě horší: může způsobit, že program nepůjde
ukončit, když bude potřeba.</p>
<p>Příkaz <code>try/except</code> proto používej
jen v situacích, kdy výjimku očekáváš – víš přesně, která chyba může
nastat a proč, a máš možnost ji opravit.
Pro nás to typicky bude načítání vstupu od uživatele.
Po špatném pokusu o zadání je dobré se ptát znovu, dokud uživatel nezadá
něco smysluplného:</p>
<div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">nacti_cislo</span><span class="p">():</span>
    <span class="k">while</span> <span class="kc">True</span><span class="p">:</span>
        <span class="n">odpoved</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s1">&#39;Zadej číslo: &#39;</span><span class="p">)</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">return</span> <span class="nb">int</span><span class="p">(</span><span class="n">odpoved</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
            <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;To nebylo číslo! Zkus to znovu.&#39;</span><span class="p">)</span>
</pre></div><h2>Další přílohy k <code>try</code></h2>
<p>Kromě <code>except</code> existují dva jiné bloky,
které můžeš „přilepit“ k <code>try</code>, a to <code>else</code> a <code>finally</code>.
První se provede, když v <code>try</code> bloku
žádná chyba nenastane; druhý se provede vždy – ať
už chyba nastala nebo ne.</p>
<p>Můžeš taky použít více bloků <code>except</code>. Provede se vždy maximálně jeden:
ten první, který danou chybu umí ošetřit.</p>
<div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">neco_udelej</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane ValueError&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">NameError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane NameError&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud nastane jiná chyba&#39;</span><span class="p">)</span>
    <span class="c1"># (kromě SystemExit a KeyboardInterrupt, ty chytat nechceme)</span>
<span class="k">except</span> <span class="ne">TypeError</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se neprovede nikdy&#39;</span><span class="p">)</span>
    <span class="c1"># (&quot;except Exception&quot; výše ošetřuje i TypeError; sem se Python nedostane)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede, pokud chyba nenastane&#39;</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s1">&#39;Tohle se provede vždycky; i pokud v `try` bloku byl např. `return`&#39;</span><span class="p">)</span>
</pre></div><h2>Úkol</h2>
<p>V domácím projektu jsme měli za úkol napsat program, který postupně načte od uživatele dvě čísla a jednoznakový řetězec – buď '+', '-', '*' nebo '/'. Program provede na číslech příslušnou operaci. Doplň program tak, aby možné chybové stavy byly ošetřeny výjimkami.</p>
<blockquote><p>Možný chybový stav může být, když chce uživatel dělit nulou.</p>
</blockquote>
<div class="solution" id="solution-0">
    <h3>Řešení</h3>
    <div class="solution-cover">
        <a href="naucse:solution?solution=0"><span class="link-text">Ukázat řešení</span></a>
    </div>
    <div class="solution-body" aria-hidden="true">
        <p>Možné řešení:</p>
<div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="c1"># Následující dvě řádky vyhodí ValueError pokud vstup není číslo</span>
    <span class="n">prvni_cislo</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&quot;Zadej první číslo: &quot;</span><span class="p">))</span>
    <span class="n">druhe_cislo</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="nb">input</span><span class="p">(</span><span class="s2">&quot;Zadej druhé číslo: &quot;</span><span class="p">))</span>

    <span class="n">operand</span> <span class="o">=</span> <span class="nb">input</span><span class="p">(</span><span class="s2">&quot;A co s nimi mám udělat? * / + nebo -  &quot;</span><span class="p">)</span>

    <span class="k">if</span> <span class="n">operand</span> <span class="o">==</span> <span class="s2">&quot;+&quot;</span><span class="p">:</span>
        <span class="n">vysledek</span> <span class="o">=</span> <span class="n">prvni_cislo</span> <span class="o">+</span> <span class="n">druhe_cislo</span>
    <span class="k">elif</span> <span class="n">operand</span> <span class="o">==</span> <span class="s2">&quot;-&quot;</span><span class="p">:</span>
        <span class="n">vysledek</span> <span class="o">=</span> <span class="n">prvni_cislo</span> <span class="o">-</span> <span class="n">druhe_cislo</span>
    <span class="k">elif</span> <span class="n">operand</span> <span class="o">==</span> <span class="s2">&quot;*&quot;</span><span class="p">:</span>
        <span class="n">vysledek</span> <span class="o">=</span> <span class="n">prvni_cislo</span> <span class="o">*</span> <span class="n">druhe_cislo</span>
    <span class="k">elif</span> <span class="n">operand</span> <span class="o">==</span> <span class="s2">&quot;/&quot;</span><span class="p">:</span>
        <span class="c1"># Pokud je `druhe_cislo` nula, následující řádka vyhodí `ZeroDivisionError`</span>
        <span class="n">vysledek</span> <span class="o">=</span> <span class="n">prvni_cislo</span> <span class="o">/</span> <span class="n">druhe_cislo</span>
    <span class="k">else</span><span class="p">:</span>
        <span class="c1"># Vstupem je operand, se kterým neumíme počítat, nebo nějaký nesmysl</span>
        <span class="c1"># S nesmyslem počítat také neumíme, takže vyhodíme `ArithmeticError`</span>
        <span class="c1"># Volba výjimky je ale na nás, vhodný by mohl být i `SyntaxError`</span>
        <span class="k">raise</span> <span class="ne">ArithmeticError</span>

<span class="k">except</span> <span class="ne">ValueError</span><span class="p">:</span>
    <span class="c1"># Zachytili jsme `ValueError` z načítání čísel</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Jedno z čísel bylo špatně zadané. Musíš být pečlivější.&quot;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ZeroDivisionError</span><span class="p">:</span>
    <span class="c1"># Tady jsme zachytili dělení nulou</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Nemůžeš dělit nulou!&quot;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ArithmeticError</span><span class="p">:</span>
    <span class="c1"># Tady jsme zachytili `ArithmeticError`, který program vyhodí</span>
    <span class="c1"># v případě špatně zadaného operátoru</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Tuhle operaci provést neumím.&quot;</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="c1"># Else větev ve spojení s `try` blokem proběhne pouze, pokud v `try` bloku</span>
    <span class="c1"># nenastala žádná vyjímka</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">prvni_cislo</span><span class="p">,</span> <span class="n">operand</span><span class="p">,</span> <span class="n">druhe_cislo</span><span class="p">,</span> <span class="s2">&quot;=&quot;</span><span class="p">,</span> <span class="n">vysledek</span><span class="p">,</span> <span class="n">sep</span><span class="o">=</span><span class="s2">&quot; &quot;</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="c1"># Tohle proběhne &quot;nakonec&quot;, ať už k nějaké vyjímce došlo nebo ne</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Děkuji za použití této skvělé kalkulačky&quot;</span><span class="p">)</span>
</pre></div>
    </div>
</div>